variables:
  CI_VERSION: "v1.0.0.${CI_PIPELINE_ID}"
  
stages:
  - build
  - package
  - deploy

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

maven-build:
  stage: build
  script: "mvn package"
  #define artifacts for next stage
  artifacts:
    paths:
    - target/exampleservice-a-0.0.1-SNAPSHOT.jar
    expire_in: 1 day
    
docker-build:
  stage: package
  script:
  - docker build -t kevinhooke/examplespringboot-a:$CI_VERSION .
  - docker push kevinhooke/examplespringboot-a:$CI_VERSION
  #tag this version also as latest
  - docker tag kevinhooke/examplespringboot-a:$CI_VERSION kevinhooke/examplespringboot-a:latest
  - docker push kevinhooke/examplespringboot-a:latest

k8s-deploy:
  stage: deploy
  script:
#  - kubectl apply -f exampleservice-a-deployment.yml
# deployment container=imagename:tag
  - kubectl set image deployment/exampleservice-a exampleservice-a=kevinhooke/examplespringboot-a:$CI_VERSION