stages:
  - build
  - package
  - deploy

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

maven-build:
  stage: build
  script: "mvn package"
  #define artifacts for next stage
  artifacts:
    paths:
    - target/exampleservice-a-0.0.1-SNAPSHOT.jar
    expire_in: 1 day
    
docker-build:
  stage: package
  script:
  - docker build -t kevinhooke/exampleservice-a:v1 .
  - docker push kevinhooke/exampleservice-a:v1

k8s-deploy:
  stage: deploy
  script:
  - kubectl apply -f exampleservice-a-deployment.yml