apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampleservice-a
  labels:
    app: exampleservice-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exampleservice-a
  template:
    metadata:
      labels:
        app: exampleservice-a
    spec:
      containers:
      - name: exampleservice-a
        image: kevinhooke/examplespringboot-a:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: exampleservice-a
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: exampleservice-b